### ISSUE TITLE
Update plugin commit SHA in Runelite plugin hub

### ISSUE THREAD

**Issue by roothorp** [MidgetJake/UniversalDiscordNotifier#34]
Hey,

It looks like this plugin has seen a number of updates and fixes since it was last updated on the plugin hub [here](https://github.com/runelite/plugin-hub/blob/master/plugins/universal-discord-notifications) (which seems to be pointing to 10c72cae85a2f8935b086ba64fc0cd9d70c0ba63). Is there a blocker preventing this, or is the plugin hub just in need of a PR?

Thanks for the great plugin!

**Comment by Felanbird** [comment]
There was a PR back in November but it was done incorrectly and then ignored until it was closed in Jan by the Runelite devs runelite/plugin-hub/pull/3571

We went ahead and forked and overhauled the plugin over in https://github.com/pajlads/DinkPlugin

**Comment by roothorp** [comment]
Awesome, thanks - appreciate it.
